export const environment = {
production: false,
oauthToken: "Bearer BQCVcy7wm28tyMC74FfhcRPtRpNjZfnIk0eFb3lQRPwXwlBBey4FBAcHq6OXy3kSTXOa3zf_xafgFxKIZtB7irOdv0hxFNP8nyqt7stkkGBZoLooK1nwMBUxeL0gyAqMl2s46CM9bkPWpZM"
};
